### ISSUE TITLE
`dist/_SassyCast.scss` is empty

### ISSUE THREAD

**Issue by montchr** [HugoGiraudel/SassyCast#6]
There's nothing in the file except for the version comment.

**Comment by hinok** [comment]
:+1:

**Comment by montchr** [comment]
Seems this was fixed in d070fa989d56596aa26649cd82cbf7abf5dd2d46. Thanks!

**Comment by hinok** [comment]
On master branch dist/_SassyCast.scss is not empty, but last tagged version 1.1.1 still has empty file.
See https://github.com/HugoGiraudel/SassyCast/blob/1.1.1/dist/_SassyCast.scss
