### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by christianmagill** [HugoGiraudel/SassyCast#7]
Pulling in from Bower indicates main file as _SassyCast.scss which only contains the line

/*! SassyCast - v1.0.0 - 2014-01-31 */

**Comment by damianmuti** [comment]
This same issue is happening to me too. Could not find a workaround so far.

**Comment by HugoGiraudel** [comment]
I will check this. :)

**Comment by HugoGiraudel** [comment]
That should be good?

**Comment by damianmuti** [comment]
Now it works as expected, Hugo.

Thanks for the celerity, mate. :)

**Comment by HugoGiraudel** [comment]
Actually rewrote the whole test suite + moved from Grunt to Gulp + moved from Bootcamp to True.

**Comment by christianmagill** [comment]
Thanks
